services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    command: server /data --console-address ":9010"
    volumes:
      - minio:/data
    environment:
      # TODO: креды будут подставляться в проде иначе
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
      - MINIO_NOTIFY_AMQP_ENABLE_IMAGE=on
      - MINIO_NOTIFY_AMQP_URL_IMAGE=amqp://admin:admin@rabbit:5672/
      - MINIO_NOTIFY_AMQP_EXCHANGE_IMAGE=test-exchange
      - MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_IMAGE=topic
      - MINIO_NOTIFY_AMQP_DURABLE_IMAGE=on
      - MINIO_NOTIFY_AMQP_ROUTING_KEY_IMAGE=s3:ObjectCreated:*
    ports:
      - "9000:9000"
      - "9010:9010"
    networks:
      - zappy

  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zappy

  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: rabbit
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - zappy

networks:
  zappy:
    driver: bridge
    name: zappy

volumes:
  minio:
  postgres:
