services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - user_service
      - catalog_service
      - review_service
    networks:
      - zappy

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    command: server /data --console-address ":9010"
    environment:
      # TODO: креды будут подставляться в проде иначе
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
      # - MINIO_NOTIFY_AMQP_ENABLE_IMAGE=on
      # - MINIO_NOTIFY_AMQP_URL_IMAGE=amqp://admin:admin@rabbit:5672/ # TODO: В будущем будет использоваться для EDA
      # - MINIO_NOTIFY_AMQP_EXCHANGE_IMAGE=test-exchange              # TODO: В будущем будет использоваться для EDA
      # - MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_IMAGE=topic                 # TODO: В будущем будет использоваться для EDA
      # - MINIO_NOTIFY_AMQP_DURABLE_IMAGE=on                          # TODO: В будущем будет использоваться для EDA
      # - MINIO_NOTIFY_AMQP_ROUTING_KEY_IMAGE=s3.ObjectCreated.Put    # TODO: В будущем будет использоваться для EDA
      - MINIO_NOTIFY_WEBHOOK_ENABLE_MIME=on
      # TODO: host.docker.internal для тестов 
      # TODO: Потом сменить на DNS
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT_MIME=http://host.docker.internal:8081/api/v1/catalog_service/webhook/checkmime
      # - MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_MIME=123                    # TODO: Токен аутентификации для Webhook-сервиса (Bearer)
      # - MINIO_NOTIFY_WEBHOOK_QUEUE_DIR_MIME=path                    # TODO: Путь к директории для хранения неотправленных сообщений
      # - MINIO_NOTIFY_WEBHOOK_CLIENT_CERT_MIME=path/to               # TODO: Путь к клиентскому сертификату для mTLS-аутентификации
      # - MINIO_NOTIFY_WEBHOOK_CLIENT_KEY_MIME=path/to                # TODO: Путь к приватному ключу для mTLS-аутентификации
    ports:
      - "9000:9000"
      - "9010:9010"
    networks:
      - zappy
    volumes:
      - minio:/data

  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - zappy
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: rabbit
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - zappy
      # volumes:
      # - rabbitmq:containerPath:ro

  vault:
    image: hashicorp/vault:1.19
    container_name: vault
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200 # TODO: DEV разработка, будет переход на TLS (HTTPS)
      - VAULT_API_ADDR=http://127.0.0.1:8200 # TODO: DEV разработка, будет переход на TLS (HTTPS)
      - VAULT_DEV_ROOT_TOKEN_ID=admin
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200 # TODO: DEV разработка, будет переход на TLS (HTTPS)
      - VAULT_UI=true
    ports:
      - "8200:8200"
    networks:
      - zappy
    volumes:
      - vault:/vault/file
      - vault:/vault/config
      - vault:/vault/logs
      - vault:/vault/plugins

  redis:
    image: redis:8.0.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - zappy
      # volumes:
      # - redis:

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./user_service/:/usr/share/nginx/html/docs/user_service
      - ./review_service/:/usr/share/nginx/html/docs/review_service
      - ./catalog_service/:/usr/share/nginx/html/docs/catalog_service
    environment:
      URLS: |
        [
          { "url": "/docs/user_service/docs/user.swagger.json", "name": "User Service" },
          { "url": "/docs/review_service/docs/review.swagger.json", "name": "Review Service" },
          { "url": "/docs/catalog_service/docs/catalog.swagger.json", "name": "Catalog Service" }
        ]
    
  review_service:
    build:
      context: ./review_service/
      dockerfile: Dockerfile
    image: review-service:1.0.0
    environment:
      - APP_LOG=dev
      - PAGINATE_SECRET=ap-P@M?8pW3vZHcCc%*chQv35s5D5R9p
      - GRPC_URL=0.0.0.0:50050
      - GRPC_TIMEOUT=5s
      - GRPC_REFLECTION=false
      - HTTP_URL=0.0.0.0:8080
      - POSTGRES_URL=postgres://postgres:admin@postgres:5432/review_service?sslmode=disable
    networks:
      - zappy
    depends_on:
      - postgres
    
  user_service:
    build:
      context: ./user_service/
      dockerfile: Dockerfile
    image: user-service:1.0.0
    environment:
      - APP_LOG=dev
      - PAGINATE_SECRET=ap-P@M?8pW3vZHcCc%*chQv35s5D5R9p
      - GRPC_URL=0.0.0.0:50051
      - GRPC_TIMEOUT=5s
      - GRPC_REFLECTION=false
      - HTTP_URL=0.0.0.0:8081
      - POSTGRES_URL=postgres://postgres:admin@postgres:5432/user_service?sslmode=disable
    networks:
      - zappy
    depends_on:
      - postgres

  catalog_service:
    build:
      context: ./catalog_service/
      dockerfile: Dockerfile
    image: catalog-service:1.0.0
    environment:
      - LOG_TYPE=dev
      - PAGINATE_SECRET=ap-P@M?8pW3vZHcCc%*chQv35s5D5R9p

      - GRPC_URL=0.0.0.0:50052
      - GRPC_TIMEOUT=5s
      - GRPC_REFLECTION=false

      - HTTP_URL=0.0.0.0:8082

      - POSTGRES_URL=postgres://postgres:admin@postgres:5432/catalog_service?sslmode=disable

      - OBJECT_STORE_OBJECT_ORIGIN=http://minio:9000
      - OBJECT_STORE_AWS_BUCKET_IMAGE=image-bucket
      - OBJECT_STORE_AWS_STAGING_BUCKET=staging-bucket
      - OBJECT_STORE_ACCESS_KEY=VDG8Aau6KOzWAosA7Jjz
      - OBJECT_STORE_SECRET_KEY=Y0hvgt8uz5MW3IYHBh7erWgvDW6ALqjGXEeMenpb

      - OBJECT_STORE_BUCKETS_IMAGE_BUCKET_NAME=/image-bucket
      - OBJECT_STORE_BUCKETS_IMAGE_BUCKET_PATH=/catalog_service/images/
      - OBJECT_STORE_BUCKETS_IMAGE_BUCKET_MIME_TYPES=image/jpeg,image/png

      - OBJECT_STORE_BUCKETS_STAGING_BUCKET_NAME=/staging-bucket
      - OBJECT_STORE_BUCKETS_STAGING_BUCKET_PATH=/catalog_service/staging/
      - OBJECT_STORE_BUCKETS_STAGING_BUCKET_MIME_TYPES=image/jpeg,image/png
    networks:
      - zappy
    depends_on:
      - postgres
      - redis
      - minio
      
  auth_service:
    build:
      context: ./auth_service/
      dockerfile: Dockerfile
    image: auth-service:1.0.0
    environment:
      - APP_LOG=dev

      - PAGINATE_SECRET=ap-P@M?8pW3vZHcCc%*chQv35s5D5R9p

      - GRPC_URL=0.0.0.0:50053
      - GRPC_TIMEOUT=5s
      - GRPC_REFLECTION=false

      - HTTP_URL=0.0.0.0:8083

      - POSTGRES_URL=postgres://postgres:admin@postgres:5432/auth_service?sslmode=disable

      - VAULT_ISSUER=auth-service
      - VAULT_APP_UUID=f7f7db8a-1827-404a-97e8-2c36595a4db4
      - VAULT_URL=http://vault:8200
      - VAULT_TOKEN=root
      - VAULT_EXPIRES=10h
      - VAULT_KEY_NAME=rsa
    networks:
      - zappy
    depends_on:
      - postgres
      - redis
      - vault

networks:
  zappy:
    driver: bridge
    name: zappy

volumes:
  minio:
  postgres:
  vault:
  rabbitmq:
  redis:
