services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    command: server /data --console-address ":9010"
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
      - AWS_ACCESS_KEY_ID=oYYBxPZd5eRUKGauMSnp
      - AWS_SECRET_ACCESS_KEY=Atszh4W1ExvcbQ6PitVUtPdAI96jANm9q34jQqkJ
      - AWS_REGION=us-east-1
      - AWS_EC2_METADATA_DISABLED=true
      - AWS_ENDPOINT_URL=http://localhost:9000
    ports:
      - "9000:9000"
      - "9010:9010"
    networks:
      - zappy

  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zappy

networks:
  zappy:
    driver: bridge
    name: zappy

volumes:
  minio:
  postgres:
