syntax = "proto3";

package wishlist.v1;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

import "validate/validate.proto";
import "common/v1/common.proto";

option go_package = "github.com/DENFNC/Zappy/user_service/proto/gen/go/v1;v1";


service WishlistItemService {
  rpc CreateWishlistItem(CreateWishlistItemRequest) 
    returns (CreateWishlistItemResponse) {
      option (google.api.http) = {
        post: "/api/v1/wishlist"
        body: "*"
    };
  }
  rpc GetWishlistItem(GetWishlistItemRequest) 
    returns (GetWishlistItemResponse) {
      option (google.api.http) = {
        get: "/api/v1/wishlist/{item_id.id}"
    };
  }
  rpc UpdateWishlistItem(UpdateWishlistItemRequest) 
    returns (UpdateWishlistItemResponse) {
      option (google.api.http) = {
        patch: "/api/v1/wishlist/{item_id.id}"
        body: "*"
    };
  }
  rpc DeleteWishlistItem(DeleteWishlistItemRequest) 
    returns (DeleteWishlistItemResponse) {
      option (google.api.http) = {
        delete: "/api/v1/wishlist/{item_id.id}"
    };
  }
  rpc ListWishlistItems(ListWishlistItemsRequest) 
    returns (ListWishlistItemsResponse) {
      option (google.api.http) = {
        get: "/api/v1/wishlist"
    };
  }
}


message WishlistItem {
  string item_id    = 1 [(validate.rules).string.uuid = true];
  string profile_id = 2 [(validate.rules).string.uuid = true];
  string product_id = 3 [(validate.rules).string.uuid = true];
  google.protobuf.Timestamp added_at = 4;
  bool   is_active  = 5;
}


message GetWishlistItemRequest {
  common.v1.ResourceID item_id = 1;
}
message GetWishlistItemResponse {
  WishlistItem wishlist_item = 1;
}


message CreateWishlistItemRequest {
  WishlistItem wishlist_item = 1;
}
message CreateWishlistItemResponse {
  common.v1.ResourceID item_id = 1;
}


message UpdateWishlistItemRequest {
  common.v1.ResourceID item_id = 1;
  WishlistItem wishlist_item = 2;
}
message UpdateWishlistItemResponse {}


message DeleteWishlistItemRequest {
  common.v1.ResourceID item_id = 1;
}
message DeleteWishlistItemResponse {}


message ListWishlistItemsRequest {
  string profile_id = 1 [(validate.rules).string.uuid = true];
  common.v1.PaginationRequest pagination = 2;
}
message ListWishlistItemsResponse {
  repeated WishlistItem wishlist_items = 1;
  common.v1.PaginationResponse pagination = 2;
}
